#!/bin/bash

regex="(feature|bug)(\/)([0-9]{1,})(-)(.*)"
branch=$(echo $(git rev-parse --abbrev-ref HEAD))

if ! [[ $branch =~ $regex ]]; then
   printf "[post-checkout] Your branch name does not follow the expected convention.\nExpected pattern is: feature/213-create-million-dollar-app\nOr see regex: $regex\nPlease rename your branch accordingly."
   exit 1
fi