// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SolidTradeServer.Data.Common;

namespace SolidTradeServer.Migrations
{
    [DbContext(typeof(DbSolidTrade))]
    [Migration("20211214180344_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SolidTradeServer.Data.Entities.AssetInfoSocieteGenerale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AssetId")
                        .HasColumnType("int");

                    b.Property<string>("AssetImageUrl")
                        .HasMaxLength(255)
                        .HasColumnType("char(255)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Currency")
                        .HasMaxLength(3)
                        .HasColumnType("char(3)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("char(128)");

                    b.Property<string>("Ticker")
                        .HasMaxLength(12)
                        .HasColumnType("char(12)");

                    b.Property<byte[]>("TimeStamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.ToTable("AssetInfosSocieteGenerale");
                });

            modelBuilder.Entity("SolidTradeServer.Data.Entities.HistoricalPosition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AssetInfoId")
                        .HasColumnType("int");

                    b.Property<float>("BuyInPrice")
                        .HasColumnType("real");

                    b.Property<int>("BuyOrSell")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("LongOrShort")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfShares")
                        .HasColumnType("int");

                    b.Property<float>("Performance")
                        .HasColumnType("real");

                    b.Property<int>("PositionType")
                        .HasColumnType("int");

                    b.Property<byte[]>("TimeStamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("AssetInfoId");

                    b.ToTable("HistoricalPositions");
                });

            modelBuilder.Entity("SolidTradeServer.Data.Entities.KnockoutDerivative", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AssetInfoId")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .HasMaxLength(6)
                        .HasColumnType("char(6)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("LongOrShort")
                        .HasColumnType("int");

                    b.Property<float>("StrikePrice")
                        .HasColumnType("real");

                    b.Property<byte[]>("TimeStamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("AssetInfoId");

                    b.ToTable("KnockoutDerivatives");
                });

            modelBuilder.Entity("SolidTradeServer.Data.Entities.KnockoutPosition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<float>("BuyInPrice")
                        .HasColumnType("real");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("KnockoutDerivativeId")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfShares")
                        .HasColumnType("int");

                    b.Property<int?>("PortfolioId")
                        .HasColumnType("int");

                    b.Property<byte[]>("TimeStamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("KnockoutDerivativeId");

                    b.HasIndex("PortfolioId");

                    b.ToTable("KnockoutPositions");
                });

            modelBuilder.Entity("SolidTradeServer.Data.Entities.OngoingKnockoutPosition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("CurrentKnockoutPositionId")
                        .HasColumnType("int");

                    b.Property<int?>("KnockoutDerivativeId")
                        .HasColumnType("int");

                    b.Property<int?>("PortfolioId")
                        .HasColumnType("int");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.Property<byte[]>("TimeStamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("CurrentKnockoutPositionId");

                    b.HasIndex("KnockoutDerivativeId");

                    b.HasIndex("PortfolioId");

                    b.ToTable("OngoingKnockoutPositions");
                });

            modelBuilder.Entity("SolidTradeServer.Data.Entities.OngoingWarrantPosition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("CurrentWarrantPositionId")
                        .HasColumnType("int");

                    b.Property<int?>("PortfolioId")
                        .HasColumnType("int");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.Property<byte[]>("TimeStamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("WarrantDerivativeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CurrentWarrantPositionId");

                    b.HasIndex("PortfolioId");

                    b.HasIndex("WarrantDerivativeId");

                    b.ToTable("OngoingWarrantPositions");
                });

            modelBuilder.Entity("SolidTradeServer.Data.Entities.Portfolio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<byte[]>("TimeStamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Portfolios");
                });

            modelBuilder.Entity("SolidTradeServer.Data.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(32)
                        .HasColumnType("char(32)");

                    b.Property<string>("Email")
                        .HasMaxLength(64)
                        .HasColumnType("char(64)");

                    b.Property<bool>("HasPublicPortfolio")
                        .HasColumnType("bit");

                    b.Property<int?>("HistoricalPositionId")
                        .HasColumnType("int");

                    b.Property<string>("ProfilePictureUrl")
                        .HasMaxLength(255)
                        .HasColumnType("char(255)");

                    b.Property<byte[]>("TimeStamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Username")
                        .HasMaxLength(32)
                        .HasColumnType("char(32)");

                    b.HasKey("Id");

                    b.HasIndex("HistoricalPositionId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SolidTradeServer.Data.Entities.WarrantDerivative", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AssetInfoId")
                        .HasColumnType("int");

                    b.Property<int>("CallOrPut")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .HasMaxLength(6)
                        .HasColumnType("char(6)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("ExpirationDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<float>("StrikePrice")
                        .HasColumnType("real");

                    b.Property<byte[]>("TimeStamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("AssetInfoId");

                    b.ToTable("WarrantDerivatives");
                });

            modelBuilder.Entity("SolidTradeServer.Data.Entities.WarrantPosition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<float>("BuyInPrice")
                        .HasColumnType("real");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("NumberOfShares")
                        .HasColumnType("int");

                    b.Property<int?>("PortfolioId")
                        .HasColumnType("int");

                    b.Property<byte[]>("TimeStamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("WarrantId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PortfolioId");

                    b.HasIndex("WarrantId");

                    b.ToTable("WarrantPositions");
                });

            modelBuilder.Entity("SolidTradeServer.Data.Entities.HistoricalPosition", b =>
                {
                    b.HasOne("SolidTradeServer.Data.Entities.AssetInfoSocieteGenerale", "AssetInfo")
                        .WithMany()
                        .HasForeignKey("AssetInfoId");

                    b.Navigation("AssetInfo");
                });

            modelBuilder.Entity("SolidTradeServer.Data.Entities.KnockoutDerivative", b =>
                {
                    b.HasOne("SolidTradeServer.Data.Entities.AssetInfoSocieteGenerale", "AssetInfo")
                        .WithMany()
                        .HasForeignKey("AssetInfoId");

                    b.Navigation("AssetInfo");
                });

            modelBuilder.Entity("SolidTradeServer.Data.Entities.KnockoutPosition", b =>
                {
                    b.HasOne("SolidTradeServer.Data.Entities.KnockoutDerivative", "KnockoutDerivative")
                        .WithMany("KnockoutPositions")
                        .HasForeignKey("KnockoutDerivativeId");

                    b.HasOne("SolidTradeServer.Data.Entities.Portfolio", "Portfolio")
                        .WithMany("KnockOutPositions")
                        .HasForeignKey("PortfolioId");

                    b.Navigation("KnockoutDerivative");

                    b.Navigation("Portfolio");
                });

            modelBuilder.Entity("SolidTradeServer.Data.Entities.OngoingKnockoutPosition", b =>
                {
                    b.HasOne("SolidTradeServer.Data.Entities.KnockoutPosition", "CurrentKnockoutPosition")
                        .WithMany()
                        .HasForeignKey("CurrentKnockoutPositionId");

                    b.HasOne("SolidTradeServer.Data.Entities.KnockoutDerivative", "KnockoutDerivative")
                        .WithMany()
                        .HasForeignKey("KnockoutDerivativeId");

                    b.HasOne("SolidTradeServer.Data.Entities.Portfolio", "Portfolio")
                        .WithMany("OngoingKnockOutPositions")
                        .HasForeignKey("PortfolioId");

                    b.Navigation("CurrentKnockoutPosition");

                    b.Navigation("KnockoutDerivative");

                    b.Navigation("Portfolio");
                });

            modelBuilder.Entity("SolidTradeServer.Data.Entities.OngoingWarrantPosition", b =>
                {
                    b.HasOne("SolidTradeServer.Data.Entities.WarrantPosition", "CurrentWarrantPosition")
                        .WithMany()
                        .HasForeignKey("CurrentWarrantPositionId");

                    b.HasOne("SolidTradeServer.Data.Entities.Portfolio", "Portfolio")
                        .WithMany("OngoingWarrantPositions")
                        .HasForeignKey("PortfolioId");

                    b.HasOne("SolidTradeServer.Data.Entities.WarrantDerivative", "WarrantDerivative")
                        .WithMany()
                        .HasForeignKey("WarrantDerivativeId");

                    b.Navigation("CurrentWarrantPosition");

                    b.Navigation("Portfolio");

                    b.Navigation("WarrantDerivative");
                });

            modelBuilder.Entity("SolidTradeServer.Data.Entities.Portfolio", b =>
                {
                    b.HasOne("SolidTradeServer.Data.Entities.User", "User")
                        .WithOne("Portfolio")
                        .HasForeignKey("SolidTradeServer.Data.Entities.Portfolio", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SolidTradeServer.Data.Entities.User", b =>
                {
                    b.HasOne("SolidTradeServer.Data.Entities.HistoricalPosition", "HistoricalPosition")
                        .WithMany()
                        .HasForeignKey("HistoricalPositionId");

                    b.Navigation("HistoricalPosition");
                });

            modelBuilder.Entity("SolidTradeServer.Data.Entities.WarrantDerivative", b =>
                {
                    b.HasOne("SolidTradeServer.Data.Entities.AssetInfoSocieteGenerale", "AssetInfo")
                        .WithMany()
                        .HasForeignKey("AssetInfoId");

                    b.Navigation("AssetInfo");
                });

            modelBuilder.Entity("SolidTradeServer.Data.Entities.WarrantPosition", b =>
                {
                    b.HasOne("SolidTradeServer.Data.Entities.Portfolio", "Portfolio")
                        .WithMany("WarrantPositions")
                        .HasForeignKey("PortfolioId");

                    b.HasOne("SolidTradeServer.Data.Entities.WarrantDerivative", "Warrant")
                        .WithMany("WarrantPositions")
                        .HasForeignKey("WarrantId");

                    b.Navigation("Portfolio");

                    b.Navigation("Warrant");
                });

            modelBuilder.Entity("SolidTradeServer.Data.Entities.KnockoutDerivative", b =>
                {
                    b.Navigation("KnockoutPositions");
                });

            modelBuilder.Entity("SolidTradeServer.Data.Entities.Portfolio", b =>
                {
                    b.Navigation("KnockOutPositions");

                    b.Navigation("OngoingKnockOutPositions");

                    b.Navigation("OngoingWarrantPositions");

                    b.Navigation("WarrantPositions");
                });

            modelBuilder.Entity("SolidTradeServer.Data.Entities.User", b =>
                {
                    b.Navigation("Portfolio");
                });

            modelBuilder.Entity("SolidTradeServer.Data.Entities.WarrantDerivative", b =>
                {
                    b.Navigation("WarrantPositions");
                });
#pragma warning restore 612, 618
        }
    }
}
